'use client';
import {useEffect,useRef,useState} from 'react';
import type {ModelProgress} from './model-download';
import {Button} from '@/components/ui/button';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {Home,Scan,Sun,Moon,NotebookPen,MousePointer2,X,ArrowLeft,Download,Info} from 'lucide-react';
const spots=[{id:'bed',title:'床边',position:[.15,-.1,-.85]},{id:'cabinet',title:'柜子旁',position:[2.35,.25,1.15]},{id:'window',title:'窗边',position:[-3.3,.05,.1]}];
export default function Page(){
 const host=useRef<HTMLDivElement>(null),api=useRef<any>(null),joy=useRef<HTMLDivElement>(null);const [status,setStatus]=useState('正在载入真实宿舍…'),[loading,setLoading]=useState(true),[ready,setReady]=useState(false),[night,setNight]=useState(false),[mode,setMode]=useState('walk'),[locked,setLocked]=useState(false),[view,setView]=useState<any>(null),[panel,setPanel]=useState<string|null>(null),[selected,setSelected]=useState('bed'),[cards,setCards]=useState<Record<string,{title:string,text:string}>>({}),[title,setTitle]=useState('床边'),[text,setText]=useState(''),[notice,setNotice]=useState(''),[stick,setStick]=useState({x:0,y:0});
 const [download,setDownload]=useState<ModelProgress|null>(null);
 const cardsRef=useRef(cards);cardsRef.current=cards;
 function openCard(id:string){const saved=cardsRef.current[id];setSelected(id);setTitle(saved?.title??spots.find(s=>s.id===id)?.title??'回忆');setText(saved?.text??'');setNotice('');setPanel('memories');api.current?.pause(true)}
 useEffect(()=>{let dead=false;const lifecycle=new AbortController();try{const v=JSON.parse(localStorage.getItem('dorm-memories-v1')??'{}');if(v&&typeof v==='object'&&!Array.isArray(v))setCards(v)}catch{}
 import('./scene').then(({createScene})=>{if(dead)return;try{api.current=createScene(host.current!,{status:setStatus,loading:setLoading,progress:setDownload,ready:setReady,mode:setMode,lock:setLocked,frame:setView,interact:()=>openCard('bed')});const ctx=(document as any).modelContext;if(ctx?.registerTool){const tool={name:'navigate_dorm',description:'切换宿舍视角或昼夜模式。',inputSchema:{type:'object',properties:{view:{type:'string',enum:['entrance','overview','walk']},lighting:{type:'string',enum:['day','night']}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['view','lighting'].includes(k))||input.view&&!['entrance','overview','walk'].includes(input.view)||input.lighting&&!['day','night'].includes(input.lighting))throw Error('参数无效');if(input.view==='entrance')api.current.home();if(input.view==='overview')api.current.overview();if(input.view==='walk')api.current.resume();if(input.lighting){const n=input.lighting==='night';setNight(n);api.current.setNight(n)}return api.current.getState()}};Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}}catch(e){setStatus('无法启动三维画面，请使用支持 WebGL 2 的浏览器');setLoading(false)}});return()=>{dead=true;lifecycle.abort();api.current?.dispose()}},[]);
 useEffect(()=>{api.current?.pause(!!panel)},[panel]);
 function save(){const next={...cards,[selected]:{title:title.trim()||'回忆',text:text.trim()}};try{localStorage.setItem('dorm-memories-v1',JSON.stringify(next));setCards(next);setNotice('已保存在此浏览器')}catch{setNotice('浏览器未允许保存，请先导出备份')}}
 function backup(){const b=new Blob([JSON.stringify(cards,null,2)],{type:'application/json'});const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download='宿舍回忆.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function joystick(e:any){const el=joy.current;if(!el)return;const r=el.getBoundingClientRect();const dx=(e.clientX-r.left-r.width/2)/42,dy=(e.clientY-r.top-r.height/2)/42;const len=Math.max(1,Math.hypot(dx,dy));setStick({x:dx/len,y:dy/len});api.current?.setJoy(dx/len,dy/len)}
 function resetJoy(){setStick({x:0,y:0});api.current?.setJoy(0,0)}
 return <main data-model-source={download?.source} data-model-cache={download?.fromCache} data-model-phase={download?.phase} data-ready={ready} data-mode={mode} data-night={night} data-yaw={view?.yaw} data-position={view?`${view.x.toFixed(3)},${view.y.toFixed(3)},${view.z.toFixed(3)}`:''}>
  <div ref={host} className="viewport"/>
  <header><div className="brand"><small><i/>揭东一中 2024 届 · 2026 制作</small><h1>揭东一中 2024 届<span>｜高三宿舍数字空间</span></h1></div><nav aria-label="场景控制">
   <Button disabled={!ready} onClick={()=>api.current?.home()} title="回到入口"><Home/> <span>回到入口</span></Button>
   <Button disabled={!ready} aria-pressed={mode==='overview'} onClick={()=>mode==='overview'?api.current?.resume():api.current?.overview()}>{mode==='overview'?<ArrowLeft/>:<Scan/>}<span>{mode==='overview'?'继续漫游':'整体俯视'}</span></Button>
   <Button disabled={!ready} aria-pressed={night} onClick={()=>{setNight(!night);api.current?.setNight(!night)}}>{night?<Moon/>:<Sun/>}<span>{night?'夜晚':'白天'}</span></Button>
   <Button aria-label="回忆卡片" onClick={()=>openCard(selected)}><NotebookPen/><span className="hide-mobile">回忆</span></Button>
   <Button aria-label="操作与修复说明" onClick={()=>setPanel('info')}><Info/></Button>
  </nav></header>
  {loading&&<div className="loading"><div className="spinner"/><p role="status">{status}</p>{download&&<div className="download-progress"><progress aria-label="模型下载进度" max={download.total} value={download.loaded}/><div>{(download.loaded/1_000_000).toFixed(2)} MB / {(download.total/1_000_000).toFixed(2)} MB</div><span>{download.fromCache?'来自本地缓存':download.source?`${download.source} · ${download.attempt}/${download.sourceCount}`:'检查本地缓存'}</span></div>}<small>保留床铺、杂物与旧时痕迹</small></div>}
  {!loading&&!ready&&<div className="loading"><p>{status}</p><Button onClick={()=>location.reload()}>重新加载</Button></div>}
  {mode==='walk'&&ready&&!panel&&<div className="reticle" aria-hidden="true"/>}
  {ready&&!panel&&view?.marks?.map((m:any,i:number)=>m.visible&&<button key={m.id} className="marker" style={{left:`${m.x}%`,top:`${m.y}%`}} aria-label={`打开${spots.find(s=>s.id===m.id)?.title}回忆`} onClick={()=>openCard(m.id)}><b>{String(i+1).padStart(2,'0')}</b><span>{spots.find(s=>s.id===m.id)?.title}</span></button>)}
  <div className="map-panel" aria-label="宿舍方位图"><svg viewBox="0 0 226 102" role="img" aria-label="床铺两侧与中央过道的示意方位图"><rect x="7" y="8" width="212" height="82" rx="3" fill="#121d23" stroke="#64757d"/><path d="M16 18H203V33H16ZM16 67H195V81H16Z" fill="#61727a" opacity=".6"/><path d="M16 50H208" stroke="#c5a56f" strokeDasharray="2 5" opacity=".4"/><text x="10" y="61" fill="#bbcacd" fontSize="10">窗</text><text x="197" y="60" fill="#bbcacd" fontSize="10">门</text>{view&&<g transform={`translate(${22+(view.x+3.4)/7*180} ${50+view.z*18}) rotate(${-view.yaw*180/Math.PI})`}><circle r="5" fill="#f5c986"/><path d="M0 -14L-4 -8H4Z" fill="#f5c986"/></g>}</svg><span>{mode==='overview'?'俯视 · 屋顶已隐藏':'过道漫游'}<small>方位示意</small></span></div>
  <div className="walk-controls">{mode==='walk'&&<><Button className="pointer-button" disabled={!ready} aria-pressed={locked} onClick={()=>api.current?.lock()}><MousePointer2/>{locked?'退出鼠标环顾（Esc）':'鼠标环顾'}</Button><p className="desktop-help"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 行走 <em>·</em> 拖动环顾 <em>·</em> 点击光点写回忆</p></>}{mode==='overview'&&<p>拖动旋转 · 滚轮缩放 · 点击「继续漫游」返回</p>}</div>
  <div className={`touch-controls ${mode!=='walk'?'hidden':''}`}><div ref={joy} className="joystick" aria-label="触屏移动摇杆" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);joystick(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))joystick(e)}} onPointerUp={resetJoy} onPointerCancel={resetJoy} onLostPointerCapture={resetJoy}><span style={{transform:`translate(${stick.x*32}px,${stick.y*32}px)`}}/></div><p>左侧移动<br/>右侧拖动环顾</p></div>
  <footer><span><i className="status-dot"/>{status}</span><span>人眼高度 1.65 m</span></footer>
  <Sheet open={!!panel} onOpenChange={open=>{if(!open){setPanel(null);setNotice('')}}}><SheetContent className="memory-sheet" showCloseButton={false}><SheetClose className="close" aria-label="关闭面板"><X/></SheetClose>
   {panel==='memories'?<><SheetHeader><small>留给那时的自己</small><SheetTitle>宿舍回忆</SheetTitle><SheetDescription>没有故事也没关系，先把这个位置留住。</SheetDescription></SheetHeader><div className="sheet-body"><div className="spot-list">{spots.map((s,i)=><Button key={s.id} variant="secondary" aria-pressed={selected===s.id} onClick={()=>openCard(s.id)}>{String(i+1).padStart(2,'0')} {s.title}</Button>)}</div><label htmlFor="memory-title">标题</label><input id="memory-title" maxLength={60} value={title} onChange={e=>setTitle(e.target.value)}/><label htmlFor="memory-text">回忆内容</label><textarea id="memory-text" maxLength={10000} placeholder="待补充回忆" value={text} onChange={e=>setText(e.target.value)}/><p className="storage-note">仅保存在此浏览器，不会上传。清除浏览器数据前，请导出备份。</p><Button className="save" onClick={save}>保存回忆</Button><p role="status" className="notice">{notice}</p><Button variant="ghost" onClick={backup}><Download/>导出已保存回忆</Button></div></>:<><SheetHeader><small>关于这一版</small><SheetTitle>重新走进宿舍</SheetTitle><SheetDescription>基于 iPad Pro 真实空间扫描，AI 辅助制作。</SheetDescription></SheetHeader><div className="sheet-body info"><h2>怎么走</h2><p>电脑：WASD 行走，拖动鼠标环顾，也可开启鼠标环顾。Esc 释放鼠标。方向键可调整视线。</p><p>触屏：左下摇杆移动，在场景右侧拖动环顾。点光点打开回忆。</p><h2>保留下来的</h2><p>床铺、柜子、杂物、床单花纹和墙面痕迹来自原始扫描。未重新排列物品，也没有添加文字、人脸或故事。</p><h2>补全与限制</h2><p>已筛除 964 个微小独立三角面，增加中性地板、墙体与天花板背衬，补面只在扫描缺口处露出。碰撞依据扫描生成，并封住两排床铺内部。</p><p>细床杆仍有弯曲和缺口，门窗外围扫描不完整。夜晚是保留可见度的氛围调整，原贴图中的日光仍会保留。</p><p className="storage-note">发布版本使用已确认可运行的扫描模型与内嵌贴图。原始扫描档案未公开上传。回忆只保存在当前浏览器。</p></div></>}
  </SheetContent></Sheet>
 </main>
}
