import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,BookOpen,Camera,Download,Expand,HelpCircle,Home,MapPin,MousePointer2,NotebookPen,Scan,Settings2,Sun,Upload,Volume2,VolumeX,X} from 'lucide-react';
import {assetURL,downloadJSON,validateHotspots,newHotspot,resolvePublished,EMPTY,DRAFT_KEY,SETTINGS_KEY,type Hotspot,type HotspotDocument,type Point} from './data';
import type {ClassroomAPI,Settings,View} from './scene';
import type {ModelProgress} from '../model-download';
import Editor from './Editor';
import Gallery from './Gallery';
import './classroom.css';

export default function Classroom(){
 const host=useRef<HTMLDivElement>(null),api=useRef<ClassroomAPI|null>(null),joy=useRef<HTMLDivElement>(null),importInput=useRef<HTMLInputElement>(null);
 const [entered,setEntered]=useState(false),[ready,setReady]=useState(false),[placeholder,setPlaceholder]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('正在准备教室…'),[progress,setProgress]=useState<ModelProgress|null>(null);
 const [document,setDocument]=useState<HotspotDocument>(EMPTY),[published,setPublished]=useState<HotspotDocument>(EMPTY),[hasDraft,setHasDraft]=useState(false),[notice,setNotice]=useState(''),[view,setView]=useState<View|null>(null);
 const [editing,setEditing]=useState(false),[relocating,setRelocating]=useState<string|null>(null),[showMarks,setShowMarks]=useState(true),[selected,setSelected]=useState<string|null>(null),[gallery,setGallery]=useState<string|null>(null),[panel,setPanel]=useState<'list'|'editor'|'help'|'settings'|null>(null);
 const [night,setNight]=useState(false),[muted,setMuted]=useState(true),[locked,setLocked]=useState(false),[stick,setStick]=useState({x:0,y:0}),[settings,setSettings]=useState<Settings|null>(null);
 const current=useRef(document);current.current=document;const revision=useRef(0);const pickRef=useRef<(p:Point)=>void>(()=>{});
 function commit(next:HotspotDocument){try{const checked=validateHotspots(next);revision.current++;current.current=checked;setDocument(checked);setHasDraft(true);try{localStorage.setItem(DRAFT_KEY,JSON.stringify(checked));setNotice('草稿已保存在此浏览器')}catch{setNotice('浏览器没有允许保存；请立即导出 JSON 备份')}}catch(e){setNotice((e as Error).message)}}
 function saveHotspot(h:Hotspot){commit({...current.current,hotspots:current.current.hotspots.map(value=>value.id===h.id?h:value)})}
 pickRef.current=(position)=>{if(relocating){const h=current.current.hotspots.find(v=>v.id===relocating);if(h){saveHotspot({...h,position});setSelected(h.id)}setRelocating(null)}else{const h=newHotspot(position);commit({...current.current,hotspots:[...current.current.hotspots,h]});setSelected(h.id)}setPanel('editor')};
 useEffect(()=>{const abort=new AbortController();let local:HotspotDocument|undefined;try{const saved=localStorage.getItem(DRAFT_KEY);if(saved){local=validateHotspots(JSON.parse(saved));setDocument(local);setHasDraft(true)}}catch{setNotice('本地草稿无法读取，已保留原记录；可以导入备份 JSON 恢复')}
  const startRevision=revision.current;fetch(assetURL('data/hotspots.json'),{signal:AbortSignal.any([abort.signal,AbortSignal.timeout(6000)]),cache:'no-store'}).then(r=>{if(!r.ok)throw Error('公开热点读取失败');return r.json()}).then(value=>{const checked=validateHotspots(value);setPublished(checked);if(!local)setDocument(previous=>resolvePublished(checked,previous,startRevision,revision.current))}).catch(()=>{if(!abort.signal.aborted)setNotice('公开热点暂未读取到，可继续创建本地草稿')});return()=>abort.abort();
 },[]);
 useEffect(()=>{if(!entered)return;let dead=false;setReady(false);setPlaceholder(false);setStatus('正在准备教室…');setError('');setView(null);setProgress(null);
  import('./scene').then(({createClassroomScene})=>{if(dead)return;try{api.current=createClassroomScene(host.current!,{status:setStatus,progress:setProgress,error:setError,lock:setLocked,frame:setView,pick:p=>pickRef.current(p),ready:isPlaceholder=>{setReady(true);setPlaceholder(isPlaceholder);api.current?.setHotspots(current.current.hotspots);try{const saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)??'null');if(saved)api.current?.configure(saved)}catch{setNotice('保存的开发参数无效，使用扫描默认设置')}setSettings(api.current?.getSettings()??null)}})}catch(e){setError('无法启动 WebGL 2。请换用支持三维画面的浏览器。');setStatus((e as Error).message)}}).catch(e=>setError((e as Error).message));
  return()=>{dead=true;api.current?.dispose();api.current=null};
 },[entered]);
 useEffect(()=>{api.current?.setHotspots(document.hotspots)},[document]);
 useEffect(()=>{api.current?.pause(!!panel||!!gallery);setStick({x:0,y:0})},[panel,gallery]);
 useEffect(()=>{api.current?.setEditing(editing)},[editing]);
 useEffect(()=>{function escape(e:KeyboardEvent){if(e.key==='Escape'){setPanel(null);setGallery(null);setRelocating(null)}}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[]);
 function openHotspot(id:string){setSelected(id);if(editing)setPanel('editor');else setGallery(id)}
 function joystick(event:React.PointerEvent){const rect=joy.current!.getBoundingClientRect(),x=(event.clientX-rect.left-rect.width/2)/40,y=(event.clientY-rect.top-rect.height/2)/40,len=Math.max(1,Math.hypot(x,y));setStick({x:x/len,y:y/len});api.current?.setJoy(x/len,y/len)}
 function resetJoy(){setStick({x:0,y:0});api.current?.setJoy(0,0)}
 async function importJSON(file?:File){if(!file)return;try{if(file.size>4*1024*1024)throw Error('热点 JSON 请小于 4 MB');const value=validateHotspots(JSON.parse(await file.text()));commit(value);setSelected(null);setPanel('list');setNotice(`已导入 ${value.hotspots.length} 个热点；已替换本机草稿`)}catch(e){setNotice(`导入失败：${(e as Error).message}`)}if(importInput.current)importInput.current.value=''}
 async function fullscreen(){try{if(window.document.fullscreenElement)await window.document.exitFullscreen();else await window.document.documentElement.requestFullscreen()}catch{setNotice('此浏览器未开放全屏，可通过系统浏览器菜单隐藏工具栏')}}
 const chosen=document.hotspots.find(h=>h.id===selected);const album=document.hotspots.find(h=>h.id===gallery);
 const dormURL=import.meta.env.BASE_URL;
 if(!entered)return <main className="classroom cl-intro">
  <div className="cl-intro-top"><a href={dormURL}><ArrowLeft size={15}/>高二宿舍</a><span>揭东一中 · 2024 届</span></div>
  <div className="cl-intro-copy"><p className="cl-eyebrow">高二教室数字空间 · 2026 制作</p><h1>Classroom<br/><em>Time Machine</em></h1><p className="cl-intro-tagline">Some places never really disappear.</p><p className="cl-intro-chinese">走回熟悉的教室。<br/>让散落的回忆，重新拥有一个位置。</p><button className="cl-enter" onClick={()=>setEntered(true)}>进入教室 <span>Enter Classroom ↗</span></button><p className="cl-intro-note">真实 iPad 扫描 · 空间记忆相册 · 可视化编辑</p></div>
  <div className="cl-intro-footer"><span>01 / 高二教室</span><a href={dormURL}>02 / 高二宿舍 →</a><span>记忆由你补充</span></div>
 </main>;
 return <main className="classroom" data-ready={ready} data-placeholder={placeholder} data-mode={view?.mode} data-focus={view?.focus?.join(',')} data-position={view?.position.join(',')} data-yaw={view?.yaw} data-model-cache={progress?.fromCache} data-hotspots={document.hotspots.length} data-editing={editing}>
  <div className="cl-viewport" ref={host}/>
  <header className="cl-header"><div><p className="cl-eyebrow">揭东一中 · 2024 届</p><h1>高二教室<span>Classroom Time Machine</span></h1></div><div className="cl-header-links"><a href={dormURL}><ArrowLeft size={14}/>高二宿舍</a><button title="返回首页" aria-label="返回首页" onClick={()=>{setEntered(false);setPanel(null);setGallery(null);setEditing(false);setNight(false)}}><Home size={17}/></button><button aria-label="操作帮助" onClick={()=>setPanel('help')}><HelpCircle size={17}/></button><button aria-label="全屏" onClick={fullscreen}><Expand size={17}/></button></div></header>
  <nav className="cl-toolbar" aria-label="教室操作">
   <button disabled={!ready} onClick={()=>api.current?.home()}><Home/>回到入口</button><button disabled={!ready} aria-pressed={view?.mode==='free'} onClick={()=>api.current?.setMode(view?.mode==='free'?'walk':'free')}><Camera/>{view?.mode==='free'?'继续漫游':'自由观察'}</button><button disabled={!ready} aria-pressed={view?.mode==='overview'} onClick={()=>api.current?.setMode(view?.mode==='overview'?'walk':'overview')}><Scan/>俯视</button>
   <button aria-pressed={showMarks} onClick={()=>setShowMarks(!showMarks)}><MapPin/>{showMarks?'隐藏热点':'显示热点'}</button><button onClick={()=>setPanel('list')}><BookOpen/>记忆相册<span className="cl-count">{document.hotspots.length}</span></button>
   <button disabled={!ready||placeholder} aria-pressed={editing} onClick={()=>{setEditing(!editing);setRelocating(null);setPanel(null);setNotice(editing?'已退出编辑':'编辑模式：点击模型表面创建热点；拖动仍可环顾')}}><NotebookPen/>{editing?'退出编辑':'编辑模式'}</button><button aria-label={muted?'打开媒体声音':'关闭媒体声音'} aria-pressed={!muted} onClick={()=>setMuted(!muted)}>{muted?<VolumeX/>:<Volume2/>}</button><button aria-label="昼夜切换" aria-pressed={night} onClick={()=>{setNight(!night);api.current?.setNight(!night)}}><Sun/></button>
  </nav>
  {!ready&&<div className="cl-loading"><div className="spinner"/><h2>{error||status}</h2>{progress&&<><progress aria-label="教室下载进度" value={progress.loaded} max={progress.total}/><p>{(progress.loaded/1e6).toFixed(2)} / {(progress.total/1e6).toFixed(2)} MB</p><small>{progress.fromCache?'来自浏览器缓存':progress.source}</small></>}<p>保留真实扫描的课桌、书本和生活痕迹</p>{error&&<button onClick={()=>location.reload()}>重新加载</button>}</div>}
  {placeholder&&<aside className="cl-model-error" role="alert"><b>当前为占位场景，真实模型未加载</b><p>{error}</p><button onClick={()=>location.reload()}>重新尝试</button></aside>}
  {ready&&!panel&&!gallery&&showMarks&&view?.marks.map((mark)=>{const h=document.hotspots.find(v=>v.id===mark.id);return h&&<button key={mark.id} className="cl-marker" style={{left:`${mark.x}%`,top:`${mark.y}%`,opacity:Math.max(.55,1-mark.distance/30)}} title={h.title} aria-label={`打开热点：${h.title}`} onClick={()=>openHotspot(h.id)}><span>◌</span><b>{h.title}</b></button>})}
  {ready&&editing&&!panel&&!gallery&&<div className="cl-edit-banner"><NotebookPen size={16}/>{relocating?'移动热点：点击新的模型表面':'点击模型表面，留下一个记忆位置'}{relocating&&<button onClick={()=>setRelocating(null)}>取消移动</button>}</div>}
  {ready&&!panel&&!gallery&&<><div className="cl-reticle"/><div className="cl-walk-help">{view?.mode==='walk'?<><button className="cl-lock" disabled={editing} onClick={()=>api.current?.lock()}><MousePointer2 size={15}/>{locked?'Esc 释放鼠标':'鼠标环顾'}</button><p>WASD 行走 · 拖动环顾 · 双击表面自由观察</p></>:<p>拖动旋转 · 滚轮 / 双指缩放 · 双击重新选中心</p>}</div><div className={`cl-touch ${view?.mode!=='walk'?'hidden':''}`}><div className="cl-joystick" ref={joy} aria-label="教室触屏移动摇杆" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);joystick(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))joystick(e)}} onPointerUp={resetJoy} onPointerCancel={resetJoy} onLostPointerCapture={resetJoy}><span style={{transform:`translate(${stick.x*30}px,${stick.y*30}px)`}}/></div><p>左侧移动<br/>右侧拖动环顾<br/>点两下表面自由观察</p></div></>}
  <footer className="cl-footer"><span>{status}</span><span>{hasDraft?'本机草稿':'公开版本'} · {view?.hiddenMarks?`${view.hiddenMarks} 个重叠标记可在相册查看 · `:''}<button aria-label="开发者模式" onClick={()=>{setSettings(api.current?.getSettings()??null);setPanel('settings')}}><Settings2 size={13}/>场景参数</button></span></footer>
  {notice&&<div className="cl-notice" role="status"><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice('')}>×</button></div>}
  {panel&&<div className="cl-panel" role="dialog" aria-modal="true" aria-label={panel==='editor'?'热点编辑面板':panel==='list'?'空间记忆列表':panel==='settings'?'开发者场景参数':'教室操作帮助'}><button className="cl-close" aria-label="关闭面板" onClick={()=>setPanel(null)}><X/></button>
   {panel==='editor'&&chosen&&<Editor key={chosen.id} hotspot={chosen} muted={muted} onSave={saveHotspot} onMove={()=>{setRelocating(chosen.id);setPanel(null)}} onDelete={()=>{commit({...current.current,hotspots:current.current.hotspots.filter(h=>h.id!==chosen.id)});setSelected(null);setPanel('list')}} onGallery={()=>{setPanel(null);setGallery(chosen.id)}}/>}
   {panel==='list'&&<><p className="cl-eyebrow">记忆有了位置</p><h2>教室记忆相册</h2><p className="cl-muted">{document.hotspots.length} 个空间热点 · {hasDraft?'正在查看本机草稿':'正在查看公开配置'}</p><div className="cl-hotspot-list">{document.hotspots.map((h,i)=><div key={h.id}><button onClick={()=>{setPanel(null);setGallery(h.id)}}><span>{String(i+1).padStart(2,'0')}</span><div><b>{h.title}</b><small>{h.date||'时间待补充'} · {h.media.length} 条媒体</small></div></button><button aria-label={`编辑${h.title}`} onClick={()=>{setSelected(h.id);setEditing(true);setPanel('editor')}}><NotebookPen size={16}/></button></div>)}{!document.hotspots.length&&<div className="cl-list-empty"><MapPin/><h3>还没有写下回忆</h3><p>进入编辑模式，点一下你的课桌、黑板或窗边，就能为它创建记忆相册。</p><button disabled={placeholder} onClick={()=>{setEditing(true);setPanel(null)}}>开始设置热点</button></div>}</div><div className="cl-panel-actions"><button onClick={()=>downloadJSON(document,'教室记忆热点.json')}><Download size={15}/>导出 JSON</button><button onClick={()=>importInput.current?.click()}><Upload size={15}/>导入 JSON</button></div><p className="cl-muted">导入会替换本机热点，建议先导出当前版本。编辑结果不会自动上传 GitHub。</p><details><summary>恢复公开版本</summary><p>先导出草稿备份。以下操作会清除这个浏览器的教室草稿。</p><button onClick={()=>{try{localStorage.removeItem(DRAFT_KEY);setDocument(published);setHasDraft(false);setNotice('已恢复公开热点配置')}catch{setNotice('浏览器不允许清除草稿')}}}>清除草稿并恢复</button></details></>}
   {panel==='help'&&<><p className="cl-eyebrow">重新走进那间教室</p><h2>操作与使用说明</h2><h3>电脑 / 手机</h3><p>电脑使用 WASD 行走，Shift 加速，鼠标拖动环顾。点「鼠标环顾」锁定光标，Esc 释放。手机左摇杆移动，右侧拖动环顾。</p><p>双击模型表面（手机连续点两下）以该点为中心自由观察，拖动旋转、滚轮或双指缩放；点「继续漫游」回到原来的位置和视线。教室俯视保留完整扫描高度，并根据屏幕比例取景。选点观察需先退出编辑模式。</p><h3>把回忆放回空间</h3><p>开启编辑模式，点击真实模型表面创建热点。填写标题、日期、描述和媒体资源路径，可重新点选位置、修改或删除。点热点打开相册；左右方向键或手机横向滑动切换媒体。</p><h3>保存与正式发布</h3><p>文字和位置自动保存到当前浏览器。导出 JSON 备份，把它放回 public/data/hotspots.json；媒体文件放进 public/memories/，再构建发布。临时本地文件预览不会保存或上传。静态网站不支持直接上传到 GitHub。</p><h3>真实扫描</h3><p>教室来自你提供的 iPad 空间扫描，OBJ 转为 GLB，未重排课桌或编造生活细节。在线贴图为 4096 像素副本，完整分辨率文件保存在本地。地板背衬和导航为独立辅助结构，扫描缺损仍保留。</p><p>昼夜调整保留可见度；原贴图中的光照无法去除。背景声音默认为关闭，只有你添加的录音和视频会播放。</p><a href={dormURL}>进入高二宿舍 →</a></>}
   {panel==='settings'&&settings&&<><p className="cl-eyebrow">开发者模式 · 本机设置</p><h2>行走与出生参数</h2><p className="cl-muted">只影响此浏览器。模型旋转、缩放和平移在 public/data/classroom-scene.json 的 transform 中配置；热点绑定模型局部坐标。</p><div className="cl-two">{([['floorY','地面高度',-20,20],['eyeHeight','人眼高度',.6,2.2],['speed','移动速度',.2,4],['radius','碰撞半径',.16,.6],['yaw','出生朝向（弧度）',-6.3,6.3]] as const).map(([key,label,min,max])=><label key={key}>{label}<input aria-label={label} type="number" step="0.01" min={min} max={max} value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}</div><label>出生位置 x / y / z</label><div className="cl-three">{settings.spawn.map((value,i)=><input key={i} aria-label={`出生坐标 ${'xyz'[i]}`} type="number" step=".05" value={value} onChange={e=>{const next=[...settings.spawn] as Point;next[i]=Number(e.target.value);setSettings({...settings,spawn:next})}}/>)}</div><button onClick={()=>setSettings({...settings,spawn:api.current!.getPosition(),yaw:view?.yaw??0})}>使用当前站立位置</button><div className="cl-panel-actions"><button className="cl-primary" onClick={()=>{try{api.current?.configure(settings);try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));setNotice('场景参数已保存在此浏览器')}catch{setNotice('参数已应用，但浏览器未允许保存')}setPanel(null)}catch(e){setNotice((e as Error).message)}}}>应用并保存</button><button onClick={()=>downloadJSON(settings,'教室行走参数.json')}>导出参数</button></div><p className="cl-muted">半径最小 0.16 m；出生点必须在可走区域。出生 y 由地面与人眼高度决定。绕 X/Z 轴改方向后需要重新生成导航，不能只改热点。</p></>}
  </div>}
  {album&&<div className="cl-modal-backdrop"><Gallery hotspot={album} muted={muted} onClose={()=>setGallery(null)} onEdit={()=>{setGallery(null);setSelected(album.id);setEditing(true);setPanel('editor')}}/></div>}
  <input ref={importInput} className="hidden" type="file" accept="application/json,.json" aria-label="导入热点 JSON" onChange={e=>void importJSON(e.target.files?.[0])}/>
 </main>;
}
